server:
  port: 0

chama-ai:
  service-discovery:
    url: http://localhost:8081
  kafka:
    group-id: notification-service-group
    bootstrap-servers: localhost:9092
    topic:
      user: user-created-topic
      notification-service: notification-service-topic
api:
  email: contact@gustavoglins.com
  security:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "POST,UPDATE,GET,DELETE"
      allowed-headers: "*"
      allowed-credentials: true
spring:
  application:
    name: notification-service
    description: API for notification management of Chama Ai.
    version: 1.0.0
    issuer: chamaai.com
    contact:
      name: Gustavo Lins
      email: gustavoglins05@gmail.com
      url: https://github.com/gustavoglins
    license:
      name: CC BY-NC 4.0
      url: https://creativecommons.org/licenses/by-nc/4.0/
    server:
      url: http://localhost:${server.port}
  datasource:
    url: jdbc:postgresql://localhost:5433/chamaai_db
    username: postgres
    password: postgres
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:admin}@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 16
resend:
  apikey: ${RESEND_API_KEY}
evolution-api:
  url: http://localhost:8080
  instance: otp
  apikey: ${EVOLUTION_API_KEY:4AmT2CKIrytgLbYj3alLg32iKaHgyexlH4j9L050jvMyjYUC4LHsIGQYUrwo3Ru1K34ZHknajmR84HNndkDjv9MKrpotl9PCGOJdZDaKn8hZ6RBMcJRgPmk326yBn2NJ}