server:
  port: 55003
chama-ai:
  kafka:
    group-id: notification-service-group
    bootstrap-servers: localhost:9092
    topic:
      user: user-created
      notification-service: notification-service-topic
  service-discovery:
    url: http://localhost:55000/eureka/
  services:
    user-service:
      url: http://localhost:55002
api:
  security:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "POST,UPDATE,GET,DELETE"
      allowed-headers: "*"
      allowed-credentials: true
spring:
  application:
    name: notification-service
    description: API for notification management of Chama Ai.
    version: 1.0.0
    issuer: chamaai.com
    contact:
      name: Gustavo Lins
      email: gustavoglins05@gmail.com
      url: https://github.com/gustavoglins
    license:
      name: CC BY-NC 4.0
      url: https://creativecommons.org/licenses/by-nc/4.0/
    server:
      url: http://localhost:${server.port}
  datasource:
    url: jdbc:postgresql://localhost:5433/chamaai_db
    username: postgres
    password: postgres
eureka:
  client:
    service-url:
      defaultZone: ${chama-ai.service-discovery.url}
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30