server:
  port: 55001
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:55000/eureka
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus





#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: user-service
#              uri: http://localhost:55002
#              predicates:
#                - Path=/users/**
#            - id: notification-service
#              uri: http://localhost:55003
#              predicates:
#                - Path=/notifications/**
#    discovery:
#      locator:
#        enabled: true
#        lower-case-service-id: true
#      client:
#        simple:
#          instances:
#            user-service:
#              - uri: http://localhost:55002
#            chat-service:
#              - uri: http://localhost:55003
#server:
#  port: 55001
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:55000/eureka
#    register-with-eureka: true
#    fetch-registry: true


#    gateway:
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/users/**
#        - id: chat-service
#          uri: lb://chat-service
#          predicates:
#            - Path=/chats/**
#        - id: auth-service
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true