api:
  security:
    cors:
      allowed-origins:
        - "http://localhost:3000"
        - "http://localhost:4200"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
      allowed-headers:
        - "*"
      allowed-credentials: true

    token:
      secret: ${PRIVATE_KEY:secret}
      public: ${PUBLIC_KEY:public}
      expiration-in-seconds: 7200
server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6380
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:admin}@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 60



#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          # put the correct url
#          issuer-uri: http://localhost:8081/realms/chamaai
#          jwk-set-uri: http://localhost:8081/auth/realms/chama/protocol/openid-connect/certs