server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6380
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:admin}@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true




#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          # put the correct url
#          issuer-uri: http://localhost:8081/realms/chamaai
#          jwk-set-uri: http://localhost:8081/auth/realms/chama/protocol/openid-connect/certs