spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chats/**
        - id: auth-service
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 55001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:55000/eureka
    register-with-eureka: true
    fetch-registry: true
