server:
  port: 0

chama-ai:
  service-discovery:
    url: http://localhost:8081
  kafka:
    group-id: user-service-group
    bootstrap-servers: localhost:9092
    topic:
      userCreated: user-created-topic
      notification-service: notification-service-topic

api:
  security:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "POST,UPDATE,GET,DELETE"
      allowed-headers: "*"
      allowed-credentials: true
    token:
      secret: ${PRIVATE_KEY:secret}
      public: ${PUBLIC_KEY:public}
spring:
  application:
    name: auth-service
    description: API for auth management, authentication and sessions in Chama Ai.
    version: 1.0.0
    issuer: chamaai.com
    contact:
      name: Gustavo Lins
      email: gustavoglins05@gmail.com
      url: https://github.com/gustavoglins
    license:
      name: CC BY-NC 4.0
      url: https://creativecommons.org/licenses/by-nc/4.0/
    server:
      url: http://localhost:${server.port}
  cloud:
    openfeign:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
  kafka:
    producer:
      retries: 5
      acks: all
      enable-idempotence: true
  datasource:
    url: jdbc:postgresql://localhost:5433/chamaai_db
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6380
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:admin}@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30