server:
  port: 55002
api:
  security:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "POST,UPDATE,GET,DELETE"
      allowed-headers: "*"
      allowed-credentials: true
    token:
      secret: ${PRIVATE_KEY:secret}
      public: ${PUBLIC_KEY:public}
      expiration-in-seconds: 7200
spring:
  application:
    name: user-service
    description: API for user management, authentication and sessions in Chama Ai.
    version: 1.0.0
    issuer: chamaai.com
    contact:
      name: Gustavo Lins
      email: gustavoglins05@gmail.com
      url: https://github.com/gustavoglins
    license:
      name: CC BY-NC 4.0
      url: https://creativecommons.org/licenses/by-nc/4.0/
    server:
      url: http://localhost:${server.port}
  cloud:
    openfeign:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
  datasource:
    url: jdbc:postgresql://localhost:5433/chamaai_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
eureka:
  client:
    service-url:
      defaultZone: ${chama-ai.services.service-discovery.url}
    register-with-eureka: true
    fetch-registry: true
chama-ai:
  services:
    service-discovery:
      url: http://localhost:55000/eureka/
    notification-service:
      url: http://localhost:55003